pipeline {
    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        REPO_URL = "https://github.com/Brathaban/Jenkins-Zero-To-Hero.git"
        MANIFEST_PATH1 = "python-jenkins-argocd-k8s/ArgocdViewing/deploy.yaml"
        MANIFEST_PATH2 = "python-jenkins-argocd-k8s/deploy/deploy.yaml"
    }

    stages {

        stage('Checkout Source') {
            steps {
                git url: "${REPO_URL}", branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                echo 'Building Docker Image'
                docker build -t brathaban123/cicd-e2e:${IMAGE_TAG} .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // English: Push Docker image to Docker Hub using Jenkins credentials
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-brathaban123') {
                        docker.image("brathaban123/cicd-e2e:${IMAGE_TAG}").push()
                    }
                }
            }
        }

  stage('Update K8s Manifest') {
            steps {
                sh '''
                 echo 'Updating deploy.yaml in main deploy file with new image tag'
                cd python-jenkins-argocd-k8s/deploy
                sed -i "s|brathaban123/cicd-e2e:.*|brathaban123/cicd-e2e:${IMAGE_TAG}|g" deploy.yaml
                echo 'Updating deploy.yaml in Argocd-viewing with new image tag'
                    cd /var/lib/jenkins/workspace/todo-app-pipeline/python-jenkins-argocd-k8s/ArgocdViewing               
                    sed -i "s|brathaban123/cicd-e2e:.*|brathaban123/cicd-e2e:${IMAGE_TAG}|g" deploy.yaml
                cat deploy.yaml
                '''
            }
        }


        stage('Commit & Push Changes') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.name "Jenkins Bot"
                    git config user.email "jenkins@local"
                    git add ${MANIFEST_PATH1} ${MANIFEST_PATH2}
                    git commit -m "Update image tag to ${IMAGE_TAG} | Jenkins Pipeline"
                    git remote set-url origin https://${GITHUB_TOKEN}@github.com/Brathaban/Jenkins-Zero-To-Hero.git
                    git push origin HEAD:main
                    '''
                }
            }
        }
    }
}
