pipeline {
  agent none 
  stages {
    stage ('ubuntu') {
      agent {
        docker {
          image 'ubuntu:22.04'
          args '-u 0'
        }
      }
      steps {
        sh '''
          whoami
          id
          set -xe
          apt-get update
          apt-get install -y git
          git --version
        '''
      }
    }
    stage ('Node-Alpine') {
      agent {
        docker { image 'node:25-alpine3.22'}
      }
      steps {
        sh 'node --version'
      }
    }
  }
}  
