pipeline {
  agent none
  stages {
    stage('Build Backend') {
      agent {
        docker { image 'maven:3.8.1-openjdk-17-slim' }
      }
      steps {
        dir('backend') {
          sh 'mvn clean install'
        }
      }
    }
    stage('Build Frontend') {
      agent {
        docker { image 'node:18-alpine' }
      }
      steps {
        dir('frontend') {
          sh 'npm install'
          sh 'node index.js'
        }
      }
    }
  }
}

