pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage ("checkout"
      steps(
       sh  "git clone"
      )
    )
    stage ("build")
    steps (
      sh "mvn clean instal"
    )
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
